### ISSUE TITLE
Strange bunch population when using bigaussian initializer in beam/distributions.py

### ISSUE THREAD

**Issue by fschuderer** [dquartul/BLonD#206]
When using the bigaussian initializer, the same, consecutive random number sequence is used to populate the beam.dt- and beam.dE-array because the random seed is set only once in line 864. When initializing N macroparticles, values 0...N-1 of this stream are used to get dt-values, values N...2N-1 to get dE-values.
Changing number of macroparticles by e.g. only 1 thus results in a completely different phase space/bunch:
- When initializing N particles, let's say that particle 1 has values dt=1 and dE=5.
- When initializing N+1 particles, particle 1 has still dt=1 but a different dE, because the former value 5 is now used as dt-value for "the new" particle N+1. dE-values are sampled from the same random stream that is used to determine dt-values.
- Indeed, we would expect to obtain exactly the same bunch as for N macroparticles, but with one additional (randomly chosen) particle N+1. Particle 1 should still have dt=1 and dE=5.

My suggestion is to use two separate random number streams for dt and dE, whereas the function parameter "seed" is used for the dt-stream and "seed+1" for the dE-stream.

**Comment by htimko** [comment]
I agree, you can insert 
np.random.seed(seed+1)
before line 868
